# -*- coding: utf-8 -*-
"""Tochegando.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w4QLNmaUFI4Igja5TTVMA2imdRrU5N9D
"""

import pandas as pd
import plotly.express as px


# import streamlit as st

df = pd.read_csv('https://raw.githubusercontent.com/Jhonweb5/DadosCovidJ/main/PS%20HSA%20%20Respostas%20ao%20formul%C3%A1rio%201.csv', encoding='utf-8')

meses = list(df["Carimbo de data/hora"].unique())
meses = st.selectbox("Selecionar mês", meses)

colunas = ['RECEPÇÃO [SIMPATIA E EDUCAÇÃO]', 'RECEPÇÃO [RAPIDEZ E EFICIÊNCIA]', 'SERVIÇO DE HOTELARIA (HIGIENIZAÇÃO/ROUPARIA)', 'SERVIÇO DE HOTELARIA [LIMPEZA/CONSERVAÇÃO]', 'SERVIÇO DE HOTELARIA (HIGIENIZAÇÃO/ROUPARIA) [ACOMODAÇÃO (MOBILIÁRIOS)]', 'SERVIÇO DE HOTELARIA (HIGIENIZAÇÃO/ROUPARIA) [ROUPA DE CAMA E BANHO]', 'MANUTENÇÃO [ESTRUTURA FÍSICA]', 'MANUTENÇÃO [RAPIDEZ E EFICIÊNCIA NO REPARO]', 'QUANTO TEMPO VOCÊ DEMOROU PRA CHEGAR AO HSA? [RESPOSTA]', 'QUAL O MEIO DE TRANSPORTE UTILIZADO? [RESPOSTA]', 'SERVIÇO SOCIAL/PSICOLOGIA/ FISIOTERAPIA [ATENDIMENTO SERVIÇO SOCIAL]', 'SERVIÇO SOCIAL/PSICOLOGIA/ FISIOTERAPIA [ATENDIMENTO PSICOLOGIA]', 'SERVIÇO SOCIAL/PSICOLOGIA/ FISIOTERAPIA [ATENDIMENTO DA FISIOTERAPIA]', 'NUTRIÇÃO [ATENDIMENTO]','NUTRIÇÃO [PONTUALIDADE DA REFEIÇÃO]', 'NUTRIÇÃO [DIETA OFERECIDA (SABOR & TEMPERATURA)]', 'SERVIÇO DE ENFERMAGEM  [SIMPATIA E EDUCAÇÃO]', 'SERVIÇO DE ENFERMAGEM  [RAPIDEZ E EFICIÊNCIA]', 'SERVIÇO DE ENFERMAGEM  [ESCLARECIMENTO DE DÚVIDAS]', 'ATENDIMENTO MÉDICO [SIMPATIA E EDUCAÇÃO]', 'ATENDIMENTO MÉDICO [RAPIDEZ E EFICIÊNCIA]', 'ATENDIMENTO MÉDICO [ESCLARECIMENTO SOBRE O TRATAMENTO]', 'VOCÊ RECOMENDARIA OS NOSSOS SERVIÇOS A PARENTES E AMIGOS? [RESPOSTA]', 'SETOR INTERNADO  [RESPOSTA]', 'QUARTO & LEITO', 'TEMPO DE ESPERA DO ATENDIMENTO?']
columnn = st.sidebar.selectbox('Qual Indicador?', colunas)







print (df.info())


df.head()

print(df.columns)

for coluna in df.columns:
    grafico = px.histogram(df, x=coluna, text_auto=True)
    grafico.show()